export const actionTypes = {
  GET_DATA: "GET_DATA",

  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

  SET_ORDERS: "SET_ORDERS",
  SET_STATES: "SET_STATES",
  SET_COVERAGE_AREA: "SET_COVERAGE_AREA",
  SET_ADDRESSES: "SET_ADDRESSES",
};
